import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import LenisProvider from "@/components/common/LenisProvider";
import TopBar from "@/components/common/TopBar";
import PopupForm from "@/components/forms/PopupForm";
import FixedIcons from "@/components/common/FixedIcons";
import FloatIcon from "@/components/common/FloatIcon";
import { ToastContainer } from "react-toastify";

export const metadata = {
  metadataBase: new URL("http://localhost:3000/"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Medpath_icon.png" />
        <style>
          @import
          url(&#39;https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap&#39;);
        </style>
      </head>
      <body
        className={`flex flex-col min-h-screen scroll-smooth overflow-y-auto`}
        suppressHydrationWarning
      >
        {/* <LenisProvider> */}
        <FloatIcon />
        <FixedIcons />
        <PopupForm />
        <TopBar />
        <Navbar />
        <div className="flex-1 flex flex-col">{children}</div>
        <Footer />
        <ToastContainer />
        {/* </LenisProvider> */}
      </body>
    </html>
  );
}
